/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SellRouteImport } from './routes/sell'
import { Route as RequestAdminRouteImport } from './routes/request-admin'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LotIdRouteImport } from './routes/lot.$id'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin/sessions'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin/sales'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin/requests'
import { Route as AuthenticatedAdminRegistrationsRouteImport } from './routes/_authenticated/admin/registrations'
import { Route as AuthenticatedAdminConsignmentsRouteImport } from './routes/_authenticated/admin/consignments'
import { Route as AuthenticatedAdminSessionsIdLotsRouteImport } from './routes/_authenticated/admin/sessions_.$id.lots'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAdminRoute = RequestAdminRouteImport.update({
  id: '/request-admin',
  path: '/request-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LotIdRoute = LotIdRouteImport.update({
  id: '/lot/$id',
  path: '/lot/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRegistrationsRoute =
  AuthenticatedAdminRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConsignmentsRoute =
  AuthenticatedAdminConsignmentsRouteImport.update({
    id: '/consignments',
    path: '/consignments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSessionsIdLotsRoute =
  AuthenticatedAdminSessionsIdLotsRouteImport.update({
    id: '/sessions_/$id/lots',
    path: '/sessions/$id/lots',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/live': typeof LiveRoute
  '/request-admin': typeof RequestAdminRoute
  '/sell': typeof SellRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/lot/$id': typeof LotIdRoute
  '/admin/consignments': typeof AuthenticatedAdminConsignmentsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/sessions/$id/lots': typeof AuthenticatedAdminSessionsIdLotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/live': typeof LiveRoute
  '/request-admin': typeof RequestAdminRoute
  '/sell': typeof SellRoute
  '/signin': typeof SigninRoute
  '/lot/$id': typeof LotIdRoute
  '/admin/consignments': typeof AuthenticatedAdminConsignmentsRoute
  '/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/sessions/$id/lots': typeof AuthenticatedAdminSessionsIdLotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/artists': typeof ArtistsRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/dispatch': typeof DispatchRoute
  '/live': typeof LiveRoute
  '/request-admin': typeof RequestAdminRoute
  '/sell': typeof SellRoute
  '/signin': typeof SigninRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/lot/$id': typeof LotIdRoute
  '/_authenticated/admin/consignments': typeof AuthenticatedAdminConsignmentsRoute
  '/_authenticated/admin/registrations': typeof AuthenticatedAdminRegistrationsRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/sessions_/$id/lots': typeof AuthenticatedAdminSessionsIdLotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/checkout'
    | '/dispatch'
    | '/live'
    | '/request-admin'
    | '/sell'
    | '/signin'
    | '/admin'
    | '/lot/$id'
    | '/admin/consignments'
    | '/admin/registrations'
    | '/admin/requests'
    | '/admin/sales'
    | '/admin/sessions'
    | '/admin/users'
    | '/admin/'
    | '/admin/sessions/$id/lots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/checkout'
    | '/dispatch'
    | '/live'
    | '/request-admin'
    | '/sell'
    | '/signin'
    | '/lot/$id'
    | '/admin/consignments'
    | '/admin/registrations'
    | '/admin/requests'
    | '/admin/sales'
    | '/admin/sessions'
    | '/admin/users'
    | '/admin'
    | '/admin/sessions/$id/lots'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/account'
    | '/artists'
    | '/auctions'
    | '/auth'
    | '/checkout'
    | '/dispatch'
    | '/live'
    | '/request-admin'
    | '/sell'
    | '/signin'
    | '/_authenticated/admin'
    | '/lot/$id'
    | '/_authenticated/admin/consignments'
    | '/_authenticated/admin/registrations'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/sessions_/$id/lots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  ArtistsRoute: typeof ArtistsRoute
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  DispatchRoute: typeof DispatchRoute
  LiveRoute: typeof LiveRoute
  RequestAdminRoute: typeof RequestAdminRoute
  SellRoute: typeof SellRoute
  SigninRoute: typeof SigninRoute
  LotIdRoute: typeof LotIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-admin': {
      id: '/request-admin'
      path: '/request-admin'
      fullPath: '/request-admin'
      preLoaderRoute: typeof RequestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot/$id': {
      id: '/lot/$id'
      path: '/lot/$id'
      fullPath: '/lot/$id'
      preLoaderRoute: typeof LotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/registrations': {
      id: '/_authenticated/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AuthenticatedAdminRegistrationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/consignments': {
      id: '/_authenticated/admin/consignments'
      path: '/consignments'
      fullPath: '/admin/consignments'
      preLoaderRoute: typeof AuthenticatedAdminConsignmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sessions_/$id/lots': {
      id: '/_authenticated/admin/sessions_/$id/lots'
      path: '/sessions/$id/lots'
      fullPath: '/admin/sessions/$id/lots'
      preLoaderRoute: typeof AuthenticatedAdminSessionsIdLotsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConsignmentsRoute: typeof AuthenticatedAdminConsignmentsRoute
  AuthenticatedAdminRegistrationsRoute: typeof AuthenticatedAdminRegistrationsRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSessionsIdLotsRoute: typeof AuthenticatedAdminSessionsIdLotsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConsignmentsRoute: AuthenticatedAdminConsignmentsRoute,
    AuthenticatedAdminRegistrationsRoute: AuthenticatedAdminRegistrationsRoute,
    AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
    AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
    AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminSessionsIdLotsRoute:
      AuthenticatedAdminSessionsIdLotsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  ArtistsRoute: ArtistsRoute,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  DispatchRoute: DispatchRoute,
  LiveRoute: LiveRoute,
  RequestAdminRoute: RequestAdminRoute,
  SellRoute: SellRoute,
  SigninRoute: SigninRoute,
  LotIdRoute: LotIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
